/*
 * @Author: Azhou
 * @Date: 2021-05-11 23:09:33
 * @LastEditors: Azhou
 * @LastEditTime: 2021-06-15 15:23:36
 */
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL'
export const UPDATE_PROJECT_DETAIL = 'UPDATE_PROJECT_DETAIL'
export const UPDATE_PROJECT_HITS = 'UPDATE_PROJECT_HITS'
export const UPDATE_CURRENT_HITS = 'UPDATE_CURRENT_HITS'
export const UPDATE_CURRENT_HIT_INDEX = 'UPDATE_CURRENT_HIT_INDEX'
export const UPDATE_BOUNDING_BOX_MAP = 'UPDATE_BOUNDING_BOX_MAP'
export const UPDATE_CURRENT_IMG_INFO = 'UPDATE_CURRENT_IMG_INFO'
